import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const RootLayout = ({ children }) => (
  <html lang="fr">
    <body className={`antialiased`}>
      {children}
    </body>
  </html>
)
