import "./globals.css"

export const metadata = {
  title: "Amazin",
  description: "Generated by create next app",
}

const RootLayout = ({ children }) => (
  <html lang="fr">
    <body className="bg-gray-100 text-gray-900">
      <header className="bg-blue-600 p-4 text-white text-center">
        <h1 className="text-2xl font-bold">Amazin</h1>
      </header>
      <main className="container mx-auto p-4">{children}</main>
      <footer className="bg-blue-600 p-4 text-white text-center">
        <p>&copy; 2024 Amazin. All rights reserved.</p>
      </footer>
    </body>
  </html>
)

export default RootLayout
